
name: Java 22 CI

on: [push]

jobs:

  nsis-jdk22:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-20.04
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "github@i2p.net"
          git config --global user.name "eyedeekay Github CI Build"
      - uses: actions/checkout@v4
      - run: wsl apt-get update
      - run: wsl apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/unsigned.sh; ls *.exe"
      - name: Upload archived copy of I2P router source embedded in the build
        uses: actions/upload-artifact@v4
        with:
          name: i2p.i2p.jpackage-build.tar.gz
          path: i2p.i2p.jpackage-build.tar.gz
      - name: Upload prebuilt jpackage bundle without any plugins or modded config
        uses: actions/upload-artifact@v4
        with:
          name: I2P-Prebuilt.zip
          path: I2P-Prebuilt.zip
      - name: Upload I2P-Easy-Install-Bundle-unsigned.exe
        uses: actions/upload-artifact@v4
        with:
          name: I2P-Easy-Install-Bundle-unsigned-jdk22.exe
          path: I2P-Easy-Install-Bundle-*.exe

  buildjpackagexe-jdk22:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/exe.sh; ls *.exe"
      - name: Upload I2P-Easy-Install-Bundle-unsigned.exe
        uses: actions/upload-artifact@v4
        with:
          name: I2P-EXE-unsigned-jdk22.exe
          path: I2P-EXE-*.exe

  buildjpackagmsi-jdk22:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/msi.sh; ls *.msi"
      - name: Upload I2P-Easy-Install-Bundle-unsigned.msi
        uses: actions/upload-artifact@v4
        with:
          name: I2P-MSI-unsigned-jdk22.msi
          path: I2P-MSI-*.msi

  buildzip-jdk22:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-20.04
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "github@i2p.net"
          git config --global user.name "eyedeekay Github CI Build"
      - uses: actions/checkout@v4
      - run: wsl apt-get update
      - run: wsl apt-cache search 7zip
      - run: wsl apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext zip p7zip-full ca-certificates
      - run: choco install wget
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/zip.sh; ls -d * */* "
      - name: Upload I2P-windows-portable.zip
        uses: actions/upload-artifact@v4
        with:
          name: I2P-windows-portable-jdk22.zip
          path: I2P-windows-portable.zip
        
  buildtgz-jdk22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - run: |
          sudo apt-get update
          sudo apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - name: build with script
        run: ./buildscripts/targz.sh; ls *.tar.gz
      - name: Upload I2P.tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: I2P-jdk22.tar.gz
          path: I2P.tar.gz
