
name: Java CI

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
  workflow_dispatch:

jobs:

  nsis:
    runs-on: windows-latest
    env:
      GITHUB_TAG: ${{ github.ref_name }}
    steps:
      - uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-20.04
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "github@i2p.net"
          git config --global user.name "eyedeekay Github CI Build"
      - uses: actions/checkout@v4
      - run: wsl apt-get update
      - run: wsl apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/unsigned.sh; ls *.exe"
      - name: Upload archived copy of I2P router source embedded in the build
        uses: actions/upload-artifact@v4
        with:
          name: i2p.i2p.jpackage-build.tar.gz
          path: i2p.i2p.jpackage-build.tar.gz
      - name: Upload prebuilt jpackage bundle without any plugins or modded config
        uses: actions/upload-artifact@v4
        with:
          name: I2P-Prebuilt.zip
          path: I2P-Prebuilt.zip
      - name: Upload I2P-Easy-Install-Bundle-unsigned.exe
        uses: actions/upload-artifact@v4
        with:
          name: I2P-Easy-Install-Bundle-unsigned.exe
          path: I2P-Easy-Install-Bundle-*.exe

  buildjpackagexe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/exe.sh; ls *.exe"
      - name: Upload I2P-Easy-Install-Bundle-unsigned.exe
        uses: actions/upload-artifact@v4
        with:
          name: I2P-EXE-unsigned.exe
          path: I2P-EXE-*.exe

  buildjpackagmsi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/msi.sh; ls *.msi"
      - name: Upload I2P-Easy-Install-Bundle-unsigned.msi
        uses: actions/upload-artifact@v4
        with:
          name: I2P-MSI-unsigned.msi
          path: I2P-MSI-*.msi

  buildzip:
    runs-on: windows-latest
    steps:
      - uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-20.04
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "github@i2p.net"
          git config --global user.name "eyedeekay Github CI Build"
      - uses: actions/checkout@v4
      - run: wsl apt-get update
      - run: wsl apt-cache search 7zip
      - run: wsl apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext zip p7zip-full ca-certificates
      - run: choco install wget
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/zip.sh; ls -d * */* "
      - name: Upload I2P-windows-portable.zip
        uses: actions/upload-artifact@v4
        with:
          name: I2P-windows-portable.zip
          path: I2P-windows-portable.zip
        
  buildtgz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          sudo apt-get update
          sudo apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - name: build with script
        run: ./buildscripts/targz.sh; ls *.tar.gz
      - name: Upload I2P.tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: I2P.tar.gz
          path: I2P.tar.gz
