
name: Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: change config
        run: |
          echo '' tee config.sh
          echo VERSIONMAJOR=2 tee config.sh
          echo VERSIONMINOR=0 tee config.sh
          echo VERSIONBUILD=0 tee config.sh
          echo I2P_VERSION=2.0.0 tee config.sh
          echo export I2P_VERSION=2.0.0 tee config.sh
          echo VERSION=master tee config.sh
          echo export VERSION=master tee config.sh
          echo '' tee config.sh
      - name: build with script
        run: bash -c "./buildscripts/exe.sh; ls *.exe"
      - name: Upload I2P-Easy-Install-Bundle-${{ github.sha }}-unsigned.exe
        uses: actions/upload-artifact@v4
        with:
          name: I2P-EXE-${{ github.sha }}-unsigned.exe
          path: I2P-EXE-2.0.0.exe
        

