
name: Java CI

on: [push]

jobs:

  nsis:
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-20.04
      - run: apt-get update
      - run: apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - run: find . -name *.sh -exec dos2unix {} \;
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: ./buildscripts/unsigned.sh; ls *.exe
      - name: Upload I2P-Easy-Install-Bundle-${{ github.sha }}-unsigned.exe
        uses: actions/upload-artifact@v4
        with:
          name: I2P-Easy-Install-Bundle-${{ github.sha }}-unsigned.exe
          path: I2P-Easy-Install-Bundle-2.4.0-unsigned.exe

  buildjpackagexe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/exe.sh; ls *.exe"
      - name: Upload I2P-Easy-Install-Bundle-${{ github.sha }}-unsigned.exe
        uses: actions/upload-artifact@v4
        with:
          name: I2P-EXE-${{ github.sha }}-unsigned.exe
          path: I2P-EXE-2.4.0.exe

  buildjpackagmsi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: bash -c "./buildscripts/msi.sh; ls *.msi"
      - name: Upload I2P-Easy-Install-Bundle-${{ github.sha }}-unsigned.msi
        uses: actions/upload-artifact@v4
        with:
          name: I2P-MSI-${{ github.sha }}-unsigned.msi
          path: I2P-MSI-2.4.0.msi

  buildzip:
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-20.04
      - run: apt-get update
      - run: apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - run: find . -name *.sh -exec dos2unix {} \;
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: build with script
        run: ./buildscripts/zip.sh; ls *.zip
      - name: Upload I2P-windows-portable-${{ github.sha }}.zip
        uses: actions/upload-artifact@v4
        with:
          name: I2P-windows-portable-${{ github.sha }}.zip
          path: I2P-windows-portable.zip
        
  buildtgz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          sudo apt-get update
          sudo apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - name: build with script
        run: ./buildscripts/targz.sh; ls *.tar.gz
      - name: Upload I2P-${{ github.sha }}.tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: I2P-${{ github.sha }}.tar.gz
          path: I2P.tar.gz
        




